HuLaSpark/HuLa

.env.development
src/services/apis.ts
src/services/http.ts
src/services/request.ts
src/utils/Worker.ts

修改请求方式采用封装fetch请求响应拦截器, 修改websocket请求地址

fix(api): 修改websocket请求地址, 修改请求方式采用fetch处理

---

src/views/homeWindow/message/Alone.vue
src/views/homeWindow/more/About.vue

fix(view): :bug: 修复打开独立窗口后主窗口消息窗口无法打开问题

---

.env.development
.env.production
src/components/common/InfoPopover.vue
src/components/rightBox/Details.vue
src/components/rightBox/MsgInput.vue
src/components/rightBox/chatBox/ChatFooter.vue
src/components/rightBox/chatBox/ChatMain.vue
src/components/rightBox/chatBox/ChatSidebar.vue
src/hooks/useLogin.ts
src/layout/left/components/InfoEdit.vue
src/layout/left/components/LeftAvatar.vue
src/layout/left/config.tsx
src/router/index.ts
src/services/apis.ts
src/services/http.ts
src/services/webSocket.ts
src/stores/chat.ts
src/stores/loginHistory.ts
src/views/LockScreen.vue
src/views/homeWindow/FriendsList.vue
src/views/homeWindow/message/index.vue
src/views/loginWindow/Login.vue
src/views/loginWindow/Register.vue

[fix(service): 🐛 修复http模块没有设置请求头导致请求报错问题](https://github.com/HuLaSpark/HuLa/commit/153896480e8a86cd50962d3678fae786ea444ebd)
[fix(view): 🐛 修复登录和请求的一些缺陷](https://github.com/HuLaSpark/HuLa/commit/54ee3ff1688ec1dd248b5e7120e3613ce8758ac9)
完善登录逻辑和自动登录逻辑

fix(service): :bug: 修复http模块没有设置请求头导致请求报错问题

---

.lintstagedrc.mjs
package.json

Chore: 只检查被修改的文件

---

docker-compose.yaml
pnpm-lock.yaml
src-tauri/tauri.conf.json
src-tauri/tauri.macos.conf.json
src-tauri/tauri.windows.conf.json
src/components/rightBox/MsgInput.vue
src/components/rightBox/chatBox/ChatFooter.vue
src/hooks/useCommon.ts

- 新增 `useCommon#insertNodeAtRange` 函数对指定 range 插入节点
- 每个 Editor 单独记录最后选区而不是在插入内容时通过 getEditorRange 获取

Fix 在 Webkit  中 re-focus 后焦点被重置

---

.husky/prepare-commit-msg

chore: 执行 git-commit 命令时出发 czg 确保 commit 规范统一

---

.gitattributes
renovate.json

fix(config): :bug: 修改renovate bot的配置

---

renovate.json

build(config): :package: 添加renovate分组更新依赖配置

---

src/components/common/InfoPopover.vue
src/components/rightBox/chatBox/ChatSidebar.vue

style: 优化InfoPopover和ChatSidebar组件的模板格式

---

src/components/windows/ActionBar.vue
src/layout/left/config.tsx
src/views/loginWindow/Login.vue

fix(view): :bug: 修复异常关闭再重新登录会不显示会话的bug

---

src/services/http.ts
src/stores/global.ts
src/stores/loginHistory.ts
src/views/registerWindow/index.vue

fix(view): :bug: 修复群里在线人数问题和登录历史记录问题

---

.github/workflows/label.yml
.github/workflows/rust-clippy.yml
package.json
pnpm-lock.yaml
src/components/rightBox/chatBox/ChatHeader.vue
src/components/rightBox/chatBox/ChatMain.vue
src/components/rightBox/renderMessage/Text.vue
src/hooks/useMsgInput.ts
src/styles/scss/chat-main.scss
src/styles/scss/msg-input.scss
src/views/registerWindow/index.vue

perf(view): :zap: 优化一下样式和登录页面的提示

---

src/components/rightBox/renderMessage/Text.vue
src/hooks/useMsgInput.ts
src/views/registerWindow/index.vue

fix(component): :bug: 修复mac下输入框输入拼音时的问题

---

.github/labeler.yml
src/components/common/VirtualList.vue
src/components/rightBox/chatBox/ChatMain.vue
src/hooks/useChatMain.ts
src/typings/components.d.ts

fix(component): :bug: 修复naiveui的虚拟列表问题

---

.github/workflows/release.yml

fix(CI): :bug: 修复release配置

---

src-tauri/gen/schemas/windows-schema.json
src-tauri/src/tray.rs

fix(rust): :bug: 修复windows启动报错问题

---

package.json
pnpm-lock.yaml
src/components/common/VirtualList.vue
src/components/rightBox/chatBox/ChatMain.vue
src/layout/index.vue
src/services/webSocket.ts
src/stores/cached.ts
src/stores/chat.ts
src/stores/group.ts
src/typings/components.d.ts
src/utils/ReadCountQueue.ts
src/views/homeWindow/message/index.vue

perf(component): :zap: 优化使用for-of

---

pnpm-lock.yaml
src-tauri/gen/schemas/windows-schema.json
src-tauri/src/tray.rs
src/hooks/useCommon.ts

fix(rust): :bug: 修复windows下启动问题

---

src-tauri/Cargo.lock
src-tauri/Cargo.toml
src-tauri/tauri.windows.conf.json
src/hooks/useMessage.ts
src/stores/global.ts

fix(windows): :bug: 修复windows下打包出错问题

---

.github/workflows/codecov.yml
src/components/rightBox/chatBox/ChatMain.vue
src/components/rightBox/emoji/index.vue
src/hooks/useCommon.ts
src/hooks/useLogin.ts
src/hooks/useMessage.ts
src/layout/left/model.tsx
src/stores/chat.ts
src/styles/scss/global/variable.scss
src/typings/components.d.ts
src/views/LockScreen.vue
src/views/homeWindow/message/index.vue

perf(component): :zap: 优化撤回消息重新编辑判定

---

.github/workflows/pr-chatbot-review.yml
src/components/rightBox/chatBox/ChatMain.vue
src/hooks/useChatMain.ts
src/services/translate.ts
src/services/types.ts
src/stores/setting.ts
src/typings/stores.d.ts
src/views/moreWindow/settings/General.vue
src/views/moreWindow/settings/config.ts

perf(component): :zap: 可在设置中切换翻译提供商

---

pnpm-lock.yaml

fix(pnpm): :bug: 更新版本依赖

---

.github/labeler.yml
.github/workflows/codecov.yml
.github/workflows/pr-chatbot-review.yml
.github/workflows/release.yml

ci: :ferris_wheel: 优化CI配置

---

.github/workflows/release.yml

fix(build): :bug: 修复ubuntu CI打包问题

---

.github/workflows/release.yml

fix(build): :bug: 修复ubuntu alsa-sys包版本

---

.github/workflows/debug-build.yml
.github/workflows/release.yml

ci(action): :ferris_wheel: 增加测试分支来测试是否可以正常打包

---

.github/workflows/debug-build.yml
.github/workflows/release.yml

Test actions

---

src-tauri/tauri.linux.conf.json
src/views/Tray.vue
src/views/homeWindow/message/index.vue

fix(component): :bug: 修复tray设置窗口大小问题

---

src/views/Notify.vue
src/views/Tray.vue

fix(view): :bug: 修复系统托盘无法变化成多列表操作

---

.gitee/ISSUE_TEMPLATE/bug.yml
.github/ISSUE_TEMPLATE/bug_report.yml
.github/ISSUE_TEMPLATE/bug_report_cn.yml
package.json
scripts/check-env.js
src/components/common/InfoPopover.vue
src/components/rightBox/chatBox/ChatHeader.vue
src/components/rightBox/chatBox/ChatSidebar.vue
src/components/rightBox/chatBox/index.vue
src/hooks/useLogin.ts
src/layout/index.vue
src/stores/global.ts
src/views/Tray.vue
src/views/homeWindow/message/index.vue

fix(common): :bug: 修复系统托盘状态切换问题

---

package.json
pnpm-lock.yaml
renovate.json

build: 升级依赖

---

.github/workflows/codecov.yml
.github/workflows/codeql.yml
.github/workflows/greetings.yml
.github/workflows/pr-chatbot-review.yml
.github/workflows/rust-clippy.yml
renovate.json

fix(renovate): :bug: 修复renovate bot配置

---

src/services/http.ts
src/services/webSocket.ts
src/utils/Worker.ts
src/views/Tray.vue

fix(service): :bug: 优化浏览器指纹

---

src/services/http.ts

feat(service): :sparkles: http请求重试

---

src/services/http.ts

Http请求重试并抛出错误

---

package.json
pnpm-lock.yaml
src-tauri/Cargo.lock
src-tauri/Cargo.toml
src-tauri/tauri.conf.json
src/components/common/InfoPopover.vue
src/components/common/LoadingSpinner.vue
src/layout/index.vue
src/layout/left/config.tsx
src/layout/left/model.tsx
src/services/fingerprint.ts
src/services/request.ts
src/typings/components.d.ts
src/views/loginWindow/Login.vue
src/workers/fingerprint.worker.ts

perf(component): :zap: 优化组件加载、浏览器指纹生成

---

src/services/webSocket.ts
src/services/wsType.ts

fix(view): :bug: 修复好友申请方不知道对方已同意的bug

---

src-tauri/src/desktops/common_cmd.rs
src/layout/left/components/ActionList.vue

fix(layout): :bug: 修复F5刷新会使窗口变大的bug

---

package.json
pnpm-lock.yaml
vite.config.ts

新增 Vue Devtools 以更快代码调试
*ps: 当开发机器性能不足时，应该禁用该插件以获得更好开发体验

feat(vite): add vite-plugin-vue-devtools for enhanced debugging

---

src/components/rightBox/MsgInput.vue
src/hooks/useCommon.ts
src/hooks/useMsgInput.ts

- 简单提取焦点管理器为 composable
- 修复 #223 由插入内容时没有正确设置光标并且设置 `<br>` 引起的 BUG
PS: 内含 TODO 内容需处理

fix(chat): 修复回复消息导致光标偏移 #223

---

src/components/rightBox/MsgInput.vue

通过 CSS 实现 placeholder 以修复处于回复时 placeholder 无法关闭 BUG

fix: Implement placeholder by CSS

---

src/hooks/useMsgInput.ts

fix(hooks): replace focus call with focusOn function in useMsgInput

---

.github/workflows/pr-chatbot-review.yml

ci(chatbot): :ferris_wheel: 修复pr-chatbot千问模型授权问题

ci(chatbot): :ferris_wheel: 修复pr-chatbot千问模型授权问题

---

src/components/rightBox/chatBox/ChatMain.vue
src/components/rightBox/chatBox/ChatSidebar.vue

#210
修复InfoPopover点击popover内部会使其关闭
#210

fix(component): :bug: 修复InfoPopover点击popover内部会使其关闭

---

src/components/rightBox/chatBox/ChatMain.vue
src/components/rightBox/chatBox/ChatSidebar.vue

点击头像的n-popover使用setShow手动触发Popover显示
closed #210

fix(component): 🐛 使用setShow手动触发Popover显示

---

src/hooks/useCommon.ts

- 修改了 useCommon 钩子中的消息类型判断条件
- 增加了对文本和表情包同时存在时的处理
- 使消息类型判断更加准确和全面

feat(hooks): 优化消息类型判断逻辑

---

src/hooks/useMsgInput.ts

feat: 回复可以回复表情包、图片

---

package.json
pnpm-lock.yaml
src-tauri/capabilities/desktop.json
src-tauri/tauri.linux.conf.json
src-tauri/tauri.macos.conf.json
src-tauri/tauri.windows.conf.json
src/App.vue
src/layout/left/model.tsx
src/router/index.ts
src/views/Update.vue

feat(view): :sparkles: 新增中版本强制更新功能

---

src/components/rightBox/chatBox/ChatFooter.vue
src/hooks/useCommon.ts
src/hooks/useMsgInput.ts

修复回复框错位BUG，该BUG可能由 https://github.com/HuLaSpark/HuLa/commit/b8c3c4eec26212a584f3e368c7b4782b2c5e8f07 引起

fix: 修复回复框错位 BUG

---

src/App.vue
src/components/rightBox/chatBox/ChatMain.vue

禁用非必要的选中和默认光标样式，使用体验更贴合Desk App

style(component): :lipstick: 更新样式以禁用全局用户选择并调整光标样式

---

package.json
src/components/rightBox/chatBox/ChatSidebar.vue

fix(component): :bug: 修复新建群,创建群公告

---

package.json
src-tauri/Cargo.toml
src-tauri/capabilities/default.json
src-tauri/src/lib.rs
src/layout/center/index.vue
src/layout/index.vue
src/services/urls.ts
src/stores/global.ts
src/views/Update.vue

fix(view): :bug: 只保持主窗口窗口大小

---

src-tauri/src/lib.rs
src/components/rightBox/chatBox/ChatMain.vue
src/layout/index.vue
src/stores/chat.ts
src/stores/group.ts
src/views/homeWindow/message/index.vue

fix: display error
